# Arreglos
Los arreglos son conjuntos ordenados de datos. Pueden estar organizados en N dimensiones, y se representan entre corchetes `[]`. Los arreglos horizontales (o vectores) contienen elementos separados por un espacio. Los arreglos verticales se separan por punto-y-coma (`;`):

In [1]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [2]:
[3;6;9]

3-element Array{Int64,1}:
 3
 6
 9

In [3]:
[2 2 2;3 3 3;4 4 4]

3×3 Array{Int64,2}:
 2  2  2
 3  3  3
 4  4  4

## Funciónes básicas
Estas son funciones básicas que operan arreglos

|Función|Descripción|
|-|-|
|eltype(A)|El tipo de elementos contenidos en A|
|length(A)|El numero de elementos contenidos en A|
|ndims(A)|Numero de dimensiones de A|
|size(A)|Tupla conteniendo las dimensiones de A|
|size(A,n)|El tamaño de A en una dimensión especifica n|
|indices(A)|Tupla conteniendo indices validos de A|
|indices(A,n)|Un rango expresando indices validos en ladimención N de A|
|eachindex(A)|Un iterador eficiente para visitar cada posición de A|

In [ ]:
A = [2 2; 3.3 2.2;"Gato" "perro"]

In [ ]:
eltype(A)

In [ ]:
length(A)

In [ ]:
ndims(A)

In [ ]:
size(A)

In [ ]:
methods(size)

In [ ]:
size(A)

## Construcción
Para construir arreglos muy grandes, a veces se necesitas ciertas funciones.

|Función|Descripción|
|-|-|
|Array{type}(dims...)|Arreglo denso sin inicializar|
|zeros(type, dims...)|Arreglo de zeros con el tipo especificado (default Float64)|
|zeros(A)|Arreglo del zeros con el mismo tipo y dimenciones que A|
|ones(type, dims...)|Arreglo de unos con el tipo especificado (default Float64)|
|ones(A)|Arreglo del zeros con el mismo tipo y dimenciones que A|
|trues(dims...)|Arreglo de booleanos con `true`s|
|trues(A)|Arreglo de booleanos con `true`s y las dimensiones de A|
|falses(dims...)|Arreglo de booleanos con `false`s|
|falses(A)|Arreglo de booleanos con `false`s y las dimensiones de A|
|reshape(A, dims...)|Un arreglo con los mismos datos que A, redimensionados|
|copy(A)|Copia A|
|deepcopy(A)|Copia A recursivamente|
|rand(dims)|Arreglo de `Float64`s con valores aleatorios distribuidos uniformemente en el rango [0,1)|
|randn(dims)|Arreglo de `Float64`s con valores aleatorios con distribución normal estandar|
|eye(n)|Matriz identidad de `n`x`n`|
|eye(m, n)|Matriz identidad de `m`x`n`|
|linspace(start, stop, n)|rango de `n` elementos distanciados de manera lineal desde `start` hasta `stop`|
|fill!(A, x)|Rellena el arreglo `A` con el valor `x`|
|fill(x, dims)|Crea un arreglo de dimenciones `dims` lleno del valor `x`|

In [ ]:
Array{Float64,2}[2.0 2.0]

In [ ]:
zeros(Float16, 250)

In [ ]:
A = [0 0 1 1 3 3; 
     1 2 3 4 5 6]

In [ ]:
ones(A)

In [ ]:
eye(A)

In [ ]:
eye(10)

In [ ]:
eye(Int,5,2)

In [ ]:
Array{Int}(round(100*rand(10,5)))

In [ ]:
A = Array{Int}(round(100*randn(5,5)))

### Algebra lineal
Al poder operar con arreglos como matrices, se pueden aplicar operadores de algebra lineal:

In [ ]:
# Inversa
A^-1

In [ ]:
# Función para la inversa de una matriz
inv(A)

In [ ]:
# Determinante
det(A)

In [ ]:
# Traspuesta
A'

In [ ]:
# Eigenvalores y Eigenvectores
eig(A)

In [ ]:
?eig

## Concatenación
|Expresión|Función|
|-|-|
|[A; B; C; ...]|vcat()|
|[A B C ...]|hcat()|
|[A B; C D; ...]|hvcat()|

In [ ]:
[A;A;A]

## Rangos unitarios
Una expresión útil en muchos casos es un rango. Para quienes tienen experiencia con MATLAB, ésta expresión será familar: `1:10`. Ésta expresión indica todos los enteros entre uno y diez. De igual forma se puede hacer en intervalos: `1:0.1:10`. Ésto significa "Cuenta del uno al diez en pasos de punto uno".
Los rangos en Julia son tipos en si, así que si preguntas a Julia solo responderá con el rango:

In [ ]:
println(typeof(1:10))
1:10

Para crear la lista de números hay que utilizar el rango de alguna forma. La más simple es `collect()`

In [ ]:
collect(1:5)'

## Comprensiones
Las comprensiones (listas de comprensión en python) son formas de crear arreglos en base a una función:

In [ ]:
[i^2 for i in 1:5]

Las comprenciones solo funcionan dentro de listas:

In [ ]:
i^2 for i in 1:5

In [ ]:
[(i,j) for i in 1:0.1:2, j in 5:10]

## Expresiones generadoras
Las mismas expresiones que se usan para las listas se pueden utilizar para algunas funciones que reciven arreglos:

In [ ]:
@time sum([i^2 for i in 1:100])

In [ ]:
@time sum(i^2 for i in 1:100)

## Vectorización de funciones
En esta libreta hemos visto funciones que pueden aplicarse a arreglos enteros. Pero las funciones unitarias pueden también aplicarse a cada elemento de un vector.

In [ ]:
exp.([1,2,3,4])

In [ ]:
f(x) = x^2

In [ ]:
f.([1,2,3,4])

# Tuplas
Las tuplas son arreglos inmutables unidimensionales y se representan como una lista de elementos separados por comas entre paréntesis.

In [ ]:
(2,3,4)

## Diccionarios
Los diccionarios permiten mapear "llaves" con valores.

In [ ]:
Dict("a" => 1, "b" => 2, "c" => 3)

Pueden ser generados con funciones generadoras.
**NOTA**: Los diccionarios no tienen un orden especifico

In [ ]:
Dict(string(Int(i)) => sin(i) for i = 0:5:45)